### ISSUE TITLE
Pretty print 'long' units with long prefixes

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/numbat#133]
If we do not have a short alias available, we should use long prefixes with the 'canonical' unit name:
```
>>> @metric_prefixes
unit points

  @metric_prefixes
  unit points

>>> megapoints

  megapoints

    = 1 Mpoints
```

So here we should print "megapoints", not "Mpoints". We want to make sure not to print anything that can not be parsed again (see also "roundtrip" tests -> this example should be added there)

**Comment by do-you-dare** [comment]
Hello! I'd like to work on this issue. Is it ok to add a new `CanonicalName` struct with the name and `AcceotsPrefix`?

**Comment by sharkdp** [comment]
Sure, sounds like a good idea
