### ISSUE TITLE
Overwrite constants and functions in the REPL

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/numbat#149]
It's a very frequent use case to go "up arrow" and change something in a let/fn definition.

**Comment by irevoire** [comment]
Hey, would the « name resolution » lazy?

Like, if I write:
```rust
let size = 80GiB
let speed = 12MiB/s
let time = size / speed
print(time) # Some duration

# Oh but I actually have to download 120GiB!
let size = 120GiB
print(time) # Should it print the old value, or recompute with the new size?
```

I don't know what's the best. In a math context, I would expect `time` to change between the two prints. But in a CS context, I would not 😬

**Comment by sharkdp** [comment]
Hm, I don't know any programming language that would 'retroactively' change the value of `time` (?).

But even if this would be a function:
```
let size = 80GiB
let speed = 12MiB/s
fn time() -> Time = size / speed
print(time())

let size = 120GiB
print(time())
```
The answer is not completely clear. If `size` and `speed` are Python-style global variables, the second `time()` call would yield the updated time value. However, if Numbat constants are more [like scoped local variables](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bcd2efd2ae9b484f9f8bb3a5e41be7b3), we would expect the `fn time` definition to capture the first value of `size`. The second definition of `size` would shadow the first one, but we would not see the updated time.

**Comment by irevoire** [comment]
> Hm, I don't know any programming language that would 'retroactively' change the value of time (?).

Yeah, neither do I; I just find it a bit strange to be able to say that, for example, `let pi = 3`. But then `π` or `τ` still keeps their old value.
But then, tbh, I find it as nice as I find it useless, so don't think too much about it 😅

**Comment by sharkdp** [comment]
For functions, this is now allowed. But not yet for variables.

**Comment by sharkdp** [comment]
Now it also works for variables.
