### ISSUE TITLE
Large numbers in pretty printing

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/numbat#152]
This is not helpful:
```
>>> let sun_luminosity = 3.828e26 W

  let sun_luminosity = 382800000000000000000000000 watt
```

**Comment by sharkdp** [comment]
Also: let's look into formatting large (integer) numbers with *spaces* as separators. Qalculate does this, and I think it's quite neat:

![image](https://github.com/sharkdp/numbat/assets/4209276/8d689710-c1c1-4197-9eea-33603af3717a)

**Comment by irevoire** [comment]
I think it would be better to use underscore so we can copy-paste it back in numbat if possible 🥺

**Comment by sharkdp** [comment]
> I think it would be better to use underscore so we can copy-paste it back in numbat if possible 🥺

For the web version, I believe that there might be a way to *show* a space, but to leave the actual content as "123456789". 

Maybe we could even make this work for the CLI version if we use a special space character, like a non-breaking space (U+00A0).

**Comment by irevoire** [comment]
Then it would be nice to accept the non-breaking-space as a valid character in the cli because they _will_ get copy-pasted.
If we do that, it could actually work in the web version as well, I guess? 🤔

**Comment by sharkdp** [comment]
> Then it would be nice to accept the non-breaking-space as a valid character in the cli because they _will_ get copy-pasted.

Yes, exactly. We could treat the non-breaking space similar to how we treat the underscore.. I assume

> If we do that, it could actually work in the web version as well, I guess? 🤔

True, yes

**Comment by sharkdp** [comment]
Decided to go with an underscore for now, as this non-breaking space caused some problems when copy pasting.
