### ISSUE TITLE
Functions that take non-dtype arguments

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/numbat#161]
Make it possible to define sth. like
```rs
fn append(s1: str, s2: str) -> str = "{s1}{s2}"

fn and(b1: bool, b2: bool) -> bool = if b1 then b2 else false
```

It also allows us to use `exchange_rate("USD")` etc. instead of having tens of different functions.

**Comment by eminence** [comment]
This might be useful to define functions that look like:

```rust
fn density(material: str) -> MassDensity { /* ... */ }
```

Using `density("water")` seems a bit nicer than having a whole bunch of `density_water`, `density_gold`, etc, constants.

**Comment by sharkdp** [comment]
@eminence Good idea. Even better would be to have some kind of `enum` type in order to avoid strings and have even more type safety.

Thinking about this, we could actually implement something like this today... with a small hack. We could introduce a unit `material_spec`:
```
unit material_spec
let water = material_spec 1
let gold = material_spec 2
```
and then use that to define the `density` function (obviously we would need a `switch` or `match` here to make this nicer for more materials):
```
fn density(material: MaterialSpec) -> MassDensity =
  if material == water
    then 1 g/cm³
    else 19.3 g/cm³
```
This could be used like so (with tab completion for materials):
```
>>> density(water)

  density(water)

    = 1 g/cm³    [MassDensity]

>>> density(gold)

  density(gold)

    = 19.3 g/cm³    [MassDensity]

```

**Comment by eminence** [comment]
A proper `enum` type would be great, but that unit type trick is clever!

**Comment by sharkdp** [comment]
This is now possible: https://numbat.dev/?q=fn+density%28material%3A+str%29+-%3E+MassDensity+%3D%0A++if+material+%3D%3D+%22water%22%0A++++then+1+g%2Fcm%C2%B3%0A++++else+if+material+%3D%3D+%22gold%22%0A+++++++++++then+19.3+g%2Fcm%C2%B3%0A+++++++++++else+0+g%2Fcm%C2%B3%0Adensity%28%22gold%22%29
