### ISSUE TITLE
Support for even more Unicode Symbols?

### ISSUE THREAD

**Issue by David-Talaga** [sharkdp/numbat#163]
Currently using a non-alphanumeric unicode character results in an error. 

For example
```
>>> let Mass_H₂O=18.0057 grams
error: while parsing
  ┌─ <input:1>:1:11
  │
1 │ let Mass_H₂O=18.0057 grams
  │           ^ Unexpected character: '₂'
```
How much trouble would allowing a broader range of unicode characters cause? 

let ⟦H₃O⁺⟧ₓ=1.2 moles/liters

**Comment by David-Talaga** [comment]
Thank you for the detailed answer. I discovered the part of Unicode that was compatible with numbat after my message. I find the Unicode subscript and superscript characters very useful for typesetting symbols, in general. My use case here is to show calculations with units for the chemistry classes I teach. We often have multiple symbols with the same dimensions. Snake case should be adequate, in principle for this purpose, but I find that a lot of my students find it confusing to learn yet another way to represent a symbol. “Extremely useful?” Probably not. “Kind of nice and cool?” Yeah. Numbat is fantastic, by the way. Thanks!-David TalagaSent from my iPhoneOn Sep 20, 2023, at 2:23 PM, David Peter ***@***.***> wrote:﻿
Thank you very much for the feedback.
We do support Unicode identifiers. We even use the official XID_START / XID_CONTINUE classes from Unicode annex #31 which was written for this exact purpose ("specifications for recommended defaults for the use of Unicode in the definitions of general-purpose identifiers").
But ⟦ and some other code points of your example are neither in XID_START, nor in XID_CONTINUE. The cited annex also has a Customization chapter, noting:

Each programming language standard has its own identifier syntax; different programming languages have different conventions for the use of certain characters such as $, @, #, and _ in identifiers. To extend such a syntax to cover the full behavior of a Unicode implementation, implementers may combine those specific rules with the syntax and properties provided here.
Each programming language can define its identifier syntax as relative to the Unicode identifier syntax, such as saying that identifiers are defined by the Unicode properties, with the addition of “$”. By addition or subtraction of a small set of language specific characters, a programming language standard can easily track a growing repertoire of Unicode characters in a compatible way.

In Numbat, we actually do this, and add certain additional characters like currency symbols ($, €, £, ¥), fractions (½, ¾, …), etc. But to be honest, I'm not sure if we can cover all use cases here. Do you think it would be extremely valuable to have something like ⟦H₃O⁺⟧ₓ as an identifier?

**Comment by sharkdp** [comment]
Understood. Thank you for your feedback. I'm always interested to hear about new use cases of Numbat.

Do you have a suggestion for Unicode code point ranges that we should allow in addition?

**Comment by David-Talaga** [comment]
Superscripts and subscripts? I’ll play around with numbat a bit more to see if anything else would be useful. Thanks!
-David

https://www.unicode.org/charts/PDF/U2070.pdf￼
U2070
PDF Document · 121 KB

**Comment by sharkdp** [comment]
Superscripts are already out of the question, I'm afraid. We currently parse something like `m⁴` as `meter^4`.

**Comment by mhmdanas** [comment]
I think subscripts at a minimum would be pretty useful. @sharkdp are you fine with adding support for them?

**Comment by sharkdp** [comment]
> I think subscripts at a minimum would be pretty useful. @sharkdp are you fine with adding support for them?

Sounds good to me!

**Comment by sharkdp** [comment]
Tentatively closing this, as we now have support for subscript characters in identifiers with #277
