### ISSUE TITLE
Aesthetics: Better Icon

### ISSUE THREAD

**Issue by archisman-panigrahi** [sharkdp/numbat#164]
This is subjective, but perhaps is worth mentioning.

The insect icon looks beautiful (both on the web app, and also on desktop). The numbat icon, when placed on desktop, looks a bit weird.
![image](https://github.com/sharkdp/numbat/assets/3063132/f403b99a-b81e-49d8-b5a5-19ec2152a823)

In my opinion, it would look more beautiful if we have a friendly looking and computer drawn icon.

Motivation: Ubuntu's shipped this wallpaper in its Raring Ringtail release
![image](https://github.com/sharkdp/numbat/assets/3063132/7b229d20-a280-4779-bb48-f434c92d5458)

This is more cute and friendly than an actual Ringtail.
![image](https://github.com/sharkdp/numbat/assets/3063132/f316efa0-7503-489e-8d49-99db55cade60)

---
This is not an urgent issue. Feel free to take your time. I also encourage other users to suggest icons.

**Comment by archisman-panigrahi** [comment]
I generated some icons with DALL-E (we don't need to decide anything right away, and don't have to necessarily choose an icon among these). We can make the background transparent.

![DALL·E 2023-09-20 09 12 05 - A cute numbat drawn digital art](https://github.com/sharkdp/numbat/assets/3063132/d0ed3b10-12db-42a6-8f55-3b7a0b6edc7a)
![DALL·E 2023-09-20 09 12 52 - A cute numbat in a bright background digital art](https://github.com/sharkdp/numbat/assets/3063132/a53a6afb-8e1b-45ef-be77-f281092f6928)
![DALL·E 2023-09-20 09 14 33 - A cute brown numbat in a bright background digital art](https://github.com/sharkdp/numbat/assets/3063132/4926a8c0-501e-44cb-94d0-626a91b65b7f)
![DALL·E 2023-09-20 09 17 25 - A cute brown numbat with pointed nose in a bright whitish background digital art](https://github.com/sharkdp/numbat/assets/3063132/5f6f84da-b642-42ec-9ce8-379e6e227e67)

**Comment by sharkdp** [comment]
Thank you for opening this. Using diffusion models for inspiration is fine, but the results are obviously not what we want...

What I have so far are the illustrations of two designers who I contracted

![2(thinner )](https://github.com/sharkdp/numbat/assets/4209276/125c681f-a3ca-4987-aaa9-b68bbea4c239)

and the one that is currently used in the repo:

![image](https://github.com/sharkdp/numbat/assets/4209276/71d4b820-cda3-4e4a-a86c-20e71133fa72)

I have also tried to create something logo-like, but I'm not a designer

![numbat-logo](https://github.com/sharkdp/numbat/assets/4209276/7e75c955-9aac-458c-a080-2994e92441d8)

Any suggestions on how to proceed are very welcome. I'd even be okay to spend a bit of money on this, but I really don't know who to contact.

**Comment by archisman-panigrahi** [comment]
![image](https://github.com/sharkdp/numbat/assets/3063132/81f1e959-ab03-45be-8c7e-8b98e7c4fc3e)
This is how these icons look on the desktop. Significantly better than the previous one (will look even better if we use SVGs).

In my opinion, [this](https://github.com/sharkdp/numbat/assets/3063132/925dd5f8-74d1-4eb2-8ea2-44b16d9f1844) icon for the large version/web version, and [the brown one](https://github.com/sharkdp/numbat/assets/3063132/1c193b25-65a2-49bc-942a-481a2af12789) (replaced with an actual SVG) for the small version/desktop app looks quite good. The black and white icon will be suitable for a high contrast version.

Small details like eyes and eyebrows will not be visible when it is used as a desktop app icon, unless the icon only shows the face, but (in my opinion) for a not-so-familiar animal like numbat, having the whole body in the icon will be more favorable than just the face.

>  I really don't know who to contact.

I don't know anyone personally either. I know that the authors of the [Papirus icon theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/) create beautiful app icons, but I don't know if they make icons from scratch for other people's project.

----

Let's keep this issue open for discussion, in case anyone has any suggestions.

**Comment by sharkdp** [comment]
Here are a few more proposals (not by me):

![image](https://github.com/sharkdp/numbat/assets/4209276/1c6a15c1-ba0d-47f2-be87-6416271d334a)


![image](https://github.com/sharkdp/numbat/assets/4209276/6c458b42-cea7-4b3d-897f-3008572afcaf)

![image](https://github.com/sharkdp/numbat/assets/4209276/5b30fbf1-20ca-44b4-8472-02dcec3fe840)

![image](https://github.com/sharkdp/numbat/assets/4209276/3a41199e-62a7-4ef2-bff0-496ead21b849)

**Comment by archisman-panigrahi** [comment]
I like https://user-images.githubusercontent.com/4209276/270666072-6c458b42-cea7-4b3d-897f-3008572afcaf.png the most among everything posted so far. I wish there were a few more stripes at back, which characterizes a numbat.

**Comment by sharkdp** [comment]
Here are a few more. Just putting them out there without any comment. Ignore the watermarks:

![image](https://github.com/sharkdp/numbat/assets/4209276/48bb8a9a-09a7-4b66-83cb-1d0418118a11)


![image](https://github.com/sharkdp/numbat/assets/4209276/9556c832-9cfc-44f5-895a-e58d0fdcd318)


![image](https://github.com/sharkdp/numbat/assets/4209276/7cf5c284-e62b-43a3-a010-5a0eec5186d4)

**Comment by archisman-panigrahi** [comment]
So far, I like https://user-images.githubusercontent.com/4209276/271198414-48bb8a9a-09a7-4b66-83cb-1d0418118a11.png the most

**Comment by sharkdp** [comment]
I added a new logo to the README and the website. I didn't really like the '+'-sign version because it reminded me of something health related (red cross). I hope everyone likes the new logo. I definitely like it better than what we had before, but I'm open for suggestions. It's a SVG file, so feel free to modify it.

Closing this for now.

**Comment by archisman-panigrahi** [comment]
I like the new logo :+1:  :+1:  :+1:

**Comment by sharkdp** [comment]
So this is closed, but look at those DALL·E 3 generated images :open_mouth:. Obviously it doesn't really know how a Numbat looks like, but still..

1
<img src="https://github.com/sharkdp/numbat/assets/4209276/09bc6b51-d344-4693-b86d-35fa3bf22a14" width="400">

2
<img src="https://github.com/sharkdp/numbat/assets/4209276/8d699b50-a636-46c1-9ea5-2d11c0d6f18f" width="400">

3
<img src="https://github.com/sharkdp/numbat/assets/4209276/7115ed3c-b702-4a57-9c41-8a786b77c322" width="400">

4
<img src="https://github.com/sharkdp/numbat/assets/4209276/d5b735d9-e2dd-4b08-9a48-2146a1b91763" width="400">

5
<img src="https://github.com/sharkdp/numbat/assets/4209276/8e6b71b0-1fb1-422b-86f3-8ece61201657" width="400">

**Comment by archisman-panigrahi** [comment]
What prompt did you use?

**Comment by sharkdp** [comment]
"A logo for a scientific calculator programming language called Numbat, which has full support for physical units."
