### ISSUE TITLE
numbat-cli tests are not standalone

### ISSUE THREAD

**Issue by joajfreitas** [sharkdp/numbat#170]
When fetching numbat-cli from https://static.crates.io/crates/numbat-cli/numbat-cli-1.6.1.crate we get a standalone crate that can be built.

However the tests cannot be run since they depend on a parent package that contains an example folder. https://github.com/sharkdp/numbat/blob/master/numbat-cli/tests/integration.rs#L66

I would propose that these external dependencies should somehow be removed.

**Comment by sharkdp** [comment]
Thank you for reporting this. I'll see if we can fix this somehow without having to move the examples into a subfolder.

**Comment by sharkdp** [comment]
@joajfreitas I hope this should work now in 1.6.2. This would allow you to uncomment the `cargo test` lines in the PKGBUILD.

There are two other things regarding packaging:
- It would be great to install the `numbat/modules` folder inside this repository to `/usr/share/numbat/` (note: that folder is also shipped with the `numbat` crate, but not with the `numbat-cli` crate), similar how we do this for the Debian packages here: https://github.com/sharkdp/numbat/blob/4926554e3eb378f166658e24a2be99c5403eca59/.github/workflows/ci.yml#L247-L249 This is not strictly necessary (those files are also included in the binary), but provides a slightly better user experience: First, users can browse those files to see what's inside Numbats standard library. And second, error messages may refer to locations inside those files (to test this, try something like `let meter = 2`, and the "previously defined here" message should point to `/usr/share/numbat/modules/units/si.nbt`)
- We are now creating binaries for other CPU architectures, if that is something of interest

**Comment by joajfreitas** [comment]
I've updated both PKGBUILDs to point to the new 1.6.2 release. Both packages now install the modules folder to `/usr/share/numbat/modules`.

I haven't yet looked into how to make the numbat-bin package support multiple architectures, but the numbat package is available for everyone right now.

**Comment by sharkdp** [comment]
It works great — thank you very much!

**Comment by archisman-panigrahi** [comment]
> I haven't yet looked into how to make the numbat-bin package support multiple architectures, but the numbat package is available for everyone right now.

Here is an example: `yay-bin` is available for several architectures. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=yay-bin
