### ISSUE TITLE
Add help command

### ISSUE THREAD

**Issue by archisman-panigrahi** [sharkdp/numbat#175]
I propose to add a `help` command (similar to insect), that will show examples of 
1. How to define new variables and units
2. How to load unused modules (like `use units::stoney`)
3. basic things like https://github.com/sharkdp/numbat/raw/master/assets/numbat-interactive.png

And it should have a link to the documentation https://numbat.dev/doc/

**Comment by sharkdp** [comment]
Yes, good idea. We can start out simple and print a link to the online documentation.
