### ISSUE TITLE
`error: while type checking` after reload with money conversion

### ISSUE THREAD

**Issue by septatrix** [sharkdp/numbat#183]
Opening the following URL shows an error: https://numbat.dev/?q=10+%E2%82%AC+to+USD. I presume that is because monetary conversion are not loaded at that point yet...

**Comment by sharkdp** [comment]
Thank you for reporting this.

Yes. The way currencies work right now is a bit of a hack: https://github.com/sharkdp/numbat/issues/177#issuecomment-1736087839

I have ideas on how to improve this situation, which would also solve your case. See https://github.com/sharkdp/numbat/issues/107 for details.

**Comment by sharkdp** [comment]
This should work now :smile:

Not just on the web, but also on the command line:
```
▶ numbat -e "10€ to $"

  10 euro ➞ dollar

    = 10.539 $    [Money]
```
