### ISSUE TITLE
Multi-line sharing

### ISSUE THREAD

**Issue by ErikDeBruijn** [sharkdp/numbat#186]
Currently, numbat.dev remembers the last command on the query part of the URL.

When sharing the link, this means that multiple lines that depend on each other, can't be shared in this way.

I was thinking of the following enhancement: If there's support for a `%0A` or some other line termination character and the instructions could be executed one by one after splitting on that character.

I'd still love to see this added. ;)

**Comment by eminence** [comment]
a related feature might be to have numbat.dev be able to load and share via gists (inspired by how https://play.rust-lang.org/ works)

**Comment by sharkdp** [comment]
I have implemented a first version of this.

Documentation: https://numbat.dev/doc/web-usage.html#sharing-calculations

Example URL for a ~5 line computation:

https://numbat.dev/?q=let+P0+%3D+50_000+people%0Alet+growth_rate+%3D+2%25+per+year%0A%0Afn+population%28t%3A+Time%29+%3D%0A++++P0+%C3%97+e%5E%28growth_rate%C2%B7t%29+%2F%2F+round%0A%0Aprint%28%22P%2820+years%29+%3D+%7Bpopulation%2820+years%29%7D%22%29

The complete "What If?" example from the tutorial, using a link shortener: https://tinyurl.com/37z9rcvu

Example URL for [the longest Numbat file I have available](https://github.com/sharkdp/numbat/blob/master/examples/numbat_syntax.nbt). Still haven't reached the URL limit

[Click](https://numbat.dev/?q=%23+This+is+a+line+comment.+It+can+span+over%0A%23+multiple+lines%0A%0A%23+1.+Imports%0A%0Ause+prelude++++++++%23+This+is+not+necessary.+The+%27prelude%27%0A+++++++++++++++++++%23+module+will+always+be+loaded+upon+startup%0A%0Ause+units%3A%3Astoney++%23+Load+a+specific+module%0A%0A%23+2.+Numbers%0A%0A12345+++++++%23+integer+notation%0A12_345++++++%23+optional+decimal+separators%0A%0A0.234+++++++%23+floating+point+notation%0A.234++++++++%23+without+the+leading+zero%0A%0A1.234e15++++%23+scientific+notation%0A1.234e%2B15%0A1e-9%0A1.0e-9%0A%0A0x2A++++++++%23+hexadecimal%0A0o52++++++++%23+octal%0A0b101010++++%23+binary%0A%0A%23+3.+Simple+expressions%0A%0A3+%2B+%284+-+3%29+++++++%23+Addition+and+subtraction%0A%0A1920+%2F+16+*+9+++++%23+Multiplication%2C+division%0A1920+%C3%B7+16+%C3%97+9+++++%23+Unicode-style%2C+%27%C2%B7%27+is+also+multiplication%0A2+pi++++++++++++++%23+Whitespace+is+implicit+multiplication%0Ameter+per+second++%23+%27per%27+keyword+can+be+used+for+division%0A%0A2%5E3+++++++++++++++%23+Exponentiation%0A2**3++++++++++++++%23+Python-style%0A2%C2%B3++++++++++++++++%23+Unicode+exponents%0A2%5E-3++++++++++++++%23+Negative+exponents%0A%0Amod%2817%2C+4%29++++++++%23+Modulo%0A%0A3+in+-%3E+cm++++++++%23+Unit+conversion%2C+can+also+be+%E2%86%92+or+%E2%9E%9E%0A3+in+to+cm++++++++%23+Unit+conversion+with+the+%27to%27+keyword%0A%0Acos%28pi%2F3+%2B+pi%29++++%23+Call+mathematical+functions%0Api%2F3+%2B+pi+%2F%2F+cos++%23+Same%2C+%27arg+%2F%2F+f%27+is+equivalent+to+%27f%28arg%29%27%0A++++++++++++++++++%23+The+%27%2F%2F%27+operator+has+the+lowest+precedence%0A++++++++++++++++++%23+which+makes+it+very+useful+for+interactive%0A++++++++++++++++++%23+terminals+%28press+up-arrow%2C+and+add+%27%2F%2F+f%27%29%0A%0A%23+4.+Constants%0A%0Alet+n+%3D+4++++++++++++++++++++++++++%23+Simple+numerical+constant%0Alet+q1+%3D+2+m%2Fs+++++++++++++++++++++%23+Right+hand+side+can+be+any+expression%0Alet+q2%3A+Speed+%3D+2+m%2Fs++++++++++++++%23+With+optional+type+annotation%0Alet+q3%3A+Length+%2F+Time+%3D+2+m%2Fs++++++%23+more+complex+type+annotation%0A%0A%23+5.+Function+definitions%0A%0Afn+foo%28z%3A+Scalar%29+-%3E+Scalar+%3D+2+*+z+%2B+3+++++++++++++++++%23+A+simple+function%0Afn+speed%28len%3A+Length%2C+dur%3A+Time%29+-%3E+Speed+%3D+len+%2F+dur+++%23+Two+parameters%0Afn+my_sqrt%3CT%3E%28q%3A+T%5E2%29+-%3E+T+%3D+q%5E%281%2F2%29++++++++++++++++++++%23+A+generic+function%0Afn+is_non_negative%28x%3A+Scalar%29+-%3E+bool+%3D+x+%E2%89%A5+0+++++++++++%23+Returns+a+bool%0A%0A%23+6.+Dimension+definitions%0A%0Adimension+Fame++++++++++++++++++++++++++++%23+A+new+base+dimension%0Adimension+Deceleration+%3D+Length+%2F+Time%5E2++%23+A+new+derived+dimension%0A%0A%23+7.+Unit+definitions%0A%0A%40aliases%28quorks%29+++++++++++++++++%23+Optional+aliases-decorator%0Aunit+quork+%3D+0.35+meter++++++++++%23+A+new+derived+unit%0A%0A%40metric_prefixes+++++++++++++++++%23+Optional+decorator+to+allow+%27milliclonk%27%2C+etc.%0A%40aliases%28ck%3A+short%29++++++++++++++%23+short+aliases+can+be+used+with+short+prefixes+%28mck%29%0Aunit+clonk%3A+Time+%3D+0.2+seconds+++%23+Optional+type+annotation%0A%0A%40metric_prefixes%0A%40aliases%28wh%3A+short%29%0Aunit+warhol%3A+Fame++++++++++++++++%23+New+base+unit+for+the+%22Fame%22+dimension%0A%0Aunit+thing+++++++++++++++++++++++%23+New+base+unit+with+automatically+generated%0A+++++++++++++++++++++++++++++++++%23+base+dimension+%22Thing%22%0A%0A%23+8.+Conditionals%0A%0Afn+step%28x%3A+Scalar%29+-%3E+Scalar+%3D+++%23+The+construct+%27if+%3Ccond%3E+then+%3Cexpr%3E+else+%3Cexpr%3E%27%0A++if+x+%3C+0+++++++++++++++++++++++%23+is+an+expression%2C+not+a+statement.+It+can+span%0A++++then+0+++++++++++++++++++++++%23+multiple+lines.%0A++++else+1%0A%0A%23+9.+Procedures%0A%0Aprint%282+kilowarhol%29++++++++++++++%23+Print+the+value+of+an+expression%0Aprint%28%22hello+world%22%29+++++++++++++%23+Print+a+message%0Aprint%28%22value+of+pi+%3D+%7Bpi%7D%22%29++++++%23+String+interpolation%0Aprint%28%22sqrt%2810%29+%3D+%7Bsqrt%2810%29%7D%22%29+++%23+Expressions+in+string+interpolation%0Aassert_eq%281+ft%2C+12+in%29+++++++++++%23+Assert+that+two+quantities+are+equal%0Aassert_eq%281+yd%2C+1+m%2C+10+cm%29++++++%23+Assert+that+two+quantities+are+equal%2C+up+to%0A+++++++++++++++++++++++++++++++++%23+the+given+precision%0Atype%282+m%2Fs%29++++++++++++++++++++++%23+Print+the+type+of+an+expression%0A)

I'd be glad to get some feedback on this. I initially implemented it using a share button, but then I figured we might not even need it... if we keep appending to the URL

**Comment by ErikDeBruijn** [comment]
Nice! That works pretty great actually!

Automating the shortening service might be something people would use, but on the other it's something people can do manually. It would be quite complex to do this with the open source version, because it probably requires API key management to a shortening service.

The "Share" button is actually something quite nice, because people won't always know that you can always copy the address bar, and they won't know it's the "latest" version with every executed command in it. By the way, I use a similar web-based service that could be good inspiration. It also has multi-line sharing implemented:
> https://numbr.dev/#new

I prefer the human-readable version to the one numbr.dev uses (base64 encoded?) because it's more transparent and perhaps even more information dense than base64.

**Comment by eminence** [comment]
For me personally, I often share URLs via IRC, so having a nice short URL is beneficial (since I can't hide a link URL behind a hyperlink).   I can take a long URL and shorten it myself using tinyurl (or any other number of URL shorteners), but having native support in numbat.dev would be nice because it makes it immediately obvious to target.   Comparing a hypothetical URL like `https://numbat.dev?share=70cf6f66ef0adad0a946ecc05897c6d4` to tinyurl, the first URL makes it immediately clear that it's going numbat.dev
