### ISSUE TITLE
Add Stefan-Boltzmann constant

### ISSUE THREAD

**Issue by archisman-panigrahi** [sharkdp/numbat#189]
I propose we add the [Stefan-Boltzmann's constant](https://wikipedia.org/en/Stefan–Boltzmann_law) to the list of predefined constants.
It comes up very often in many astronomical calculations.

We can perhaps call it either `stefan_boltzmann_constant` or `stefan_constant` in numbat, and also denote it as `sigma` and `σ` (note: that requires editing the example https://github.com/sharkdp/numbat/blob/8d52de96ca341a21b9316cb86737b466718db9d3/examples/typecheck_error/non_scalar_exponent.nbt to because a dummy variable sigma is used there).

**Comment by sharkdp** [comment]
Sounds good. Thank you.

> (note: that requires editing the example https://github.com/sharkdp/numbat/blob/8d52de96ca341a21b9316cb86737b466718db9d3/examples/typecheck_error/non_scalar_exponent.nbt to because a dummy variable sigma is used there).

Maybe we can refrain from using sigma/σ for now? and just add `stefan_boltzmann_constant`?

**Comment by archisman-panigrahi** [comment]
> Maybe we can refrain from using sigma/σ for now? and just add `stefan_boltzmann_constant`?

That's fine :+1:
