### ISSUE TITLE
Create IRC channel

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/numbat#192]
it would be really great if there were an official IRC channel for Numbat (perhaps on https://libera.chat), to facilitate a more synchronous and informal communication medium as compared to GitHub. @sharkdp is this fine with you? If you don't feel like joining and/or managing the channel, I'm happy to do that myself.

**Comment by sharkdp** [comment]
Sure — let's try it out and see if anyone joins :smile:. If you could manage that, that would be great. I'd be glad to join.

**Comment by mhmdanas** [comment]
Sound goods! I registered #numbat on Libera.chat; if it proves successful, we can formally register a group on Libera.chat later (though it's not a hard requirement). It's also a good idea to document the existence of this channel somewhere in Numbat's documentation (and in the software itself maybe?).
