### ISSUE TITLE
Create tree-sitter grammar

### ISSUE THREAD

**Issue by mhmdanas** [sharkdp/numbat#213]
So that editors like Helix can show Numbat files with syntax highlighting.

**Comment by sharkdp** [comment]
https://github.com/irevoire/tree-sitter-numbat

FYI @irevoire

**Comment by mhmdanas** [comment]
Oh, nice, I didn't notice that! I'll submit a PR to Helix to add the grammar there if it wasn't already done.

**Comment by irevoire** [comment]
Hey, sorry it’s not quite finished yet 😅 
It may be a bit early to push it into helix.
+ I didn't write the highlighting file (it seems easy, but I didn't find the time to do it)

**Comment by irevoire** [comment]
Hey, I’ll be honest, I stopped working on it currently because I have a bug with tree-sitter that I do not understand at all.

I opened an issue on their side, but no one is answering 😢 

My parser seems to work for most stuff, but it doesn't work for _numbers_ which is a big issue, check out: https://github.com/tree-sitter/tree-sitter/issues/2735 if you want to help me.

**Comment by sharkdp** [comment]
> heck out: [tree-sitter/tree-sitter#2735](https://github.com/tree-sitter/tree-sitter/issues/2735) if you want to help me.

I did a bit of debugging myself and I think I found the problem. See upstream ticket for more information.

**Comment by irevoire** [comment]
Totally unlocked me, and the parser is looking pretty good, there are still some bugs remaining here and there, but I’m making progress.

I started working on the highlighter now, and I’m making good progress as well 😁 
<img width="553" alt="image" src="https://github.com/sharkdp/numbat/assets/7032172/2a85cabd-b4cf-4485-a1db-dad0ab8fba2a">

I still have a bunch of stuff to implement before even trying to propose it to `helix`, but I’m starting to see how I could finish this project!

**Comment by mhmdanas** [comment]
Since somebody's already working on this, I'll close this issue for now.

@irevoire let us know whenever the grammar is ready and then we can drop a link to it in the repo somewhere. :)

**Comment by mhmdanas** [comment]
> Hey, sorry, I had some health issues and couldn't code much since last time.

I hope you're getting better! And no worries, we're all volunteers here, there are no obligations.

> It would be great if you could try it through and let me know everything that doesn't work. I'm starting to code again

Sure, I'll let you know how it goes.
