### ISSUE TITLE
decibels not supported, temperatures not documented

### ISSUE THREAD

**Issue by severak** [sharkdp/numbat#217]
It seems that decibels are not supported while documentation list it in [supported units](https://numbat.dev/doc/list-units.html). 

I can understand why because I work on [similar library](https://github.com/severak/graph-paper/blob/main/severak/units.md) myself.

There is also no mention that Celsius or Farenheit needs to be converted to Kelvin before use. 

I can understand why this but I think general public would like to convert between these two.

**Comment by sharkdp** [comment]
> It seems that decibels are not supported while documentation list it in [supported units](https://numbat.dev/doc/list-units.html).

Oops. That is a leftover from Insect, which actually supported decibel/bel — to a certain extent.

You can get back a similar behavior by adding
```
@metric_prefixes
unit bel
```
to your `~/.config/numbat/init.nbt` file. But I doubt that its very helpful. See https://github.com/sharkdp/insect/issues/279 for a related discussion.

How would you ideally like to use the bel/decibel units in Numbat?

> There is also no mention that Celsius or Farenheit needs to be converted to Kelvin before use.

Please see #184 

> I can understand why this but I think general public would like to convert between these two.

I agree.

**Comment by sharkdp** [comment]
> It seems that decibels are not supported while documentation list it in [supported units](https://numbat.dev/doc/list-units.html).

This is now fixed.

**Comment by severak** [comment]
> How would you ideally like to use the bel/decibel units in Numbat?

This is what I am not sure about. This is why I asked in this comment.

But approach described in #[279](https://github.com/sharkdp/insect/issues/279) sounds interesting, maybe I will try this in my library (even though I am not sure if this is actually usable).

**Comment by sharkdp** [comment]
Ok, I'll close this for now. Please feel free to open a new ticket if you have a concrete feature request.
