### ISSUE TITLE
Remove more styling when  `--pretty-print=never` is set

### ISSUE THREAD

**Issue by 0xAdk** [sharkdp/numbat#237]
I have recently been trying out numbat and how it compares to qalc.

My main use case is quick cli calculations
```sh
$ qalc -t '8 GiB to MiB'
8192 MiB
$ qalc -t
> 8 GiB to MiB

  8192 MiB

>
```
For numbat though I'm not able to get the same level of brevity.

The closest I can get to this with numbat is `--pretty-print=never`
```sh
$ numbat --pretty-print=never -e '8 GiB to MiB'
    = 8192 MiB    [DigitalInformation]

$ numbat -q --pretty-print=never
>>> 8 GiB to MiB

    = 8192 MiB    [DigitalInformation]

>>>
```

I was wondering if it would make sense to have formatting closer to qalc when `--pretty-print=never` is set, and if a PR would be welcome for these changes
```sh
$ numbat --pretty-print=never -e '8 GiB to MiB'
8192 MiB
$ numbat -q --pretty-print=never
>>> 8 GiB to MiB

  8192 MiB

>>>
```

Additionally It would be nice get close to `qalc -t` in use, so maybe `-e` could default to `--pretty-print=never`?
Or add an option `-t` as an alias for `--pretty-print=never`
```sh
$ numbat -e '8 GiB to MiB'
8192 MiB
$ # or
$ numbat -te '8 GiB to MiB'
8192 MiB
$ numbat -qt
>>> 8 GiB to MiB

  8192 MiB

>>>
```

**Comment by 0xAdk** [comment]
also, if `numbat -e` should default to no pretty printing, what about `echo 1 + 1 | numbat`

**Comment by mhmdanas** [comment]
> Additionally It would be nice get close to qalc -t in use, so maybe -e could default to --pretty-print=never?

This was the default behavior in Insect, and I agree it makes sense not to pretty-print in non-interactive mode by default (even without passing `--pretty-print=never`). Adding a new command-line flag for this isn't necessary in my opinion.

> also, if numbat -e should default to no pretty printing, what about echo 1 + 1 | numbat

Both shouldn't pretty-print IMO.

**Comment by sharkdp** [comment]
> I was wondering if it would make sense to have formatting closer to qalc when `--pretty-print=never` is set, and if a PR would be welcome for these changes

Yes :+1: 

> Additionally It would be nice get close to `qalc -t` in use, so maybe `-e` could default to `--pretty-print=never`?

Yes, good idea

> also, if `numbat -e` should default to no pretty printing, what about `echo 1 + 1 | numbat`

I also think that the "`stdin` is not a terminal" case should be handled the same way as `numbat -e`.
