### ISSUE TITLE
Improve usability of the `ls` command

### ISSUE THREAD

**Issue by Bzero** [sharkdp/numbat#239]
Currently the `ls` command seems a bit inconvenient to use for me since it outputs a long, yet a bit sparse list of text requiring a lot of scrolling to find the variable, function or unit I am actually looking for.

To improve I would suggest two changes:

  * Use a multi-column layout to reduce the vertical space a bit and to get an immediate glance on all defined variables/functions.
  * Add subcommands `ls variables`, `ls functions`, `ls units` and `ls dimensions` to add the possibility to list only variables, functions, units or dimensions, respectively.

**Comment by sharkdp** [comment]
Thank you for the feedback — I fully agree!

> Use a multi-column layout to reduce the vertical space a bit and to get an immediate glance on all defined variables/functions.

:+1: 

> Add subcommands ls variables, ls functions, ls units and ls dimensions to add the possibility to list only variables, functions, units or dimensions, respectfully.

:+1: 

Maybe we can also come up with a syntax to specifically look up *length* units, for example? Like `ls units Length`. Because that should be fairly easy to implement as well.

**Comment by sharkdp** [comment]
Released in https://github.com/sharkdp/numbat/releases/tag/v1.8.0

**Comment by Bzero** [comment]
Very nice, thanks a lot!
