### ISSUE TITLE
feature request: lowercase currencies

### ISSUE THREAD

**Issue by j-lakeman** [sharkdp/numbat#284]
Love the versatility of Numbat!

Would be great if one could type currencies in lowercase like that:

<pre>
  █▄░█ █░█ █▀▄▀█ █▄▄ ▄▀█ ▀█▀    Numbat 1.9.0
  █░▀█ █▄█ █░▀░█ █▄█ █▀█ ░█░    https://numbat.dev/

<b>&gt;&gt;&gt; </b>1 eur -&gt; usd
<font color="#EF2929"><b>error</b></font><b>: while type checking</b>
  <font color="#3465A4">┌─</font> &lt;input:1&gt;:1:3
  <font color="#3465A4">│</font>
<font color="#3465A4">1</font> <font color="#3465A4">│</font> 1 <font color="#CC0000">eur</font> -&gt; usd
  <font color="#3465A4">│</font>   <font color="#CC0000">^^^</font> <font color="#CC0000">unknown identifier</font>
  <font color="#3465A4">│</font>
  <font color="#3465A4">=</font> Did you mean &apos;EUR&apos;?

</pre>

It's already pretty much guessing “EUR” right.
IMHO this way one could look up conversion rates a lot quicker.

**Comment by sharkdp** [comment]
I'd rather not do this by default, to be honest. You can use `€` and `$` if you want something shorter. And you can add something like
```
unit eur = EUR
unit usd = USD
```
in your init.nbt file, if you like (https://numbat.dev/doc/cli-customization.html)
