### ISSUE TITLE
feature request: not multiplying but converting currencies

### ISSUE THREAD

**Issue by j-lakeman** [sharkdp/numbat#285]
Here Numbat tries to multiply the currencies:

<pre><b>&gt;&gt;&gt; </b>1 EUR USD

  <font color="#C4A000">1</font> <font color="#06989A">euro</font> <b>×</b> <font color="#06989A">dollar</font>

    <b>=</b> <font color="#C4A000">0.899766</font> <font color="#06989A">€²</font><font color="#AAAAAA">    [</font><font color="#3465A4"><i>Money²</i></font><font color="#AAAAAA">]</font>
</pre>

IMHO it would make a lot more sense to convert the first given currency into the second one. In DuckDuckGo something like that is possible:

https://duckduckgo.com/?q=eur+usd&ia=web

In combination with #284 this could greatly improve the ease of use of Numbat regarding currencies.

**Comment by eminence** [comment]
In general, putting two units next to each other will multiply them (for example `V A` or `s A`).  While it's true that currencies are already a little bit special in numbat, I don't think it makes sense to break from the standard tradition of multiplication here.

**Comment by mhmdanas** [comment]
You can convert currencies like any other units using the conversion operator:
```
>>> USD to EUR

  dollar ➞ euro

    = 0.904977 €    [Money]
```

In fact, I'd argue it's more sensible and consistent that currency conversion works like other unit conversions in Numbat. And of course, this is consistent with Numbat's philosophy of not being too "smart".
