### ISSUE TITLE
`ampere × volt` not simplified to `watt`

### ISSUE THREAD

**Issue by walking-octopus** [sharkdp/numbat#286]
## Current output:

```
>>> 10 A * 11 V

  10 ampere × 11 volt

    = 110 A·V    [Power]

>>> 10 A * 11 V to W

  10 ampere × 11 volt ➞ watt

    = 110 W    [Power]
```

## Expected output:

```
>>> 10 A * 11 V

  10 ampere × 11 volt

    = 110 W    [Power]
```

I might be misunderstanding how the unit system is expected to behave, but I expect it to simplify to lowest terms, which in this case is 110 W... If this is not the expected behavior, perhaps it can be worth consideration to make it a display option.

**Comment by sharkdp** [comment]
> I might be misunderstanding how the unit system is expected to behave, but I expect it to simplify to lowest terms, which in this case is 110 W.

You are not misunderstanding anything. This should be simplified to 110 W, yes. See #89 for details. Hopefully, we can resolve this once #116 is implemented — something I certainly plan to do.
