### ISSUE TITLE
Add binary, octal, and decimal conversion

### ISSUE THREAD

**Issue by apcamargo** [sharkdp/numbat#289]
v1.9.0 added hex conversion support. It would be useful to have the same for binary, octal and decimal numbers.

**Comment by sharkdp** [comment]
Agreed. Maybe @masa300V would be willing to add his `bin` solution (https://github.com/sharkdp/numbat/discussions/283#discussioncomment-7950560) in a PR?

`oct` should be straigtforward as well.

decimal is not needed, IMO — as that is the default.

**Comment by apcamargo** [comment]
I can see conversion to decimal being useful in cases where the user has a binary/oct/hex that they got somewhere else and just want to convert it to decimal. This might be outside of Numbat's scope, though.

**Comment by eminence** [comment]
numbat accepts literals like `0xff` or `0b110011` or `0o77`

Does this do what you want for decimal conversions?

**Comment by apcamargo** [comment]
It does! Thanks!

**Comment by nycex** [comment]
It would be great if the alternate-base support would extend to non-integers:
e.g. I sometimes need a conversion like `bin(0.25) => 0b0.01` or `0b0.01 => 0.25`

**Comment by SollyBunny** [comment]
Just a suggestion but there could be extra format attribute(s) that each number has.  20 is decimal, 0b10 is bin, if you do 0b10 + 20 then the output is whichever base is closer to 10 meaning you can do 0b100 + 0b011 and the output will be 0b111. you could also convert between them with similar syntax to units 5 -> base(7) with popular bases having aliases of bin(ary),dec(imal),oct(ernary). this sytem could also be expandded to support roman numerals and forced mantissa, exponent / purely positional notation

**Comment by sharkdp** [comment]
`bin` and `oct` are now implemented. They will feel even more natural once we implement #202. Please feel free to open tickets for the remaining issues.
