### ISSUE TITLE
Inconsistent symbols for ohm short alias

### ISSUE THREAD

**Issue by eminence** [sharkdp/numbat#299]
The ohm unit currently is defined with a short alias `Ω` (U+03A9 GREEK CAPITAL LETTER OMEGA)

In the unicode_input.rs, we have the `\ohm` shortcut mapped to `Ω` (U+2126 OHM SIGN)

This inconsistency should be fixed.  I think I'd like to change the short alias, but technically this is a breaking change (existing NBT scripts that reference the omega symbol will be broken).   But we could also consider changing the `\ohm` mapping to use the omega symbol instead of the ohm symbol.

Thoughts on which of these two we should change?

**Comment by Bzero** [comment]
I think the most straightforward way would be to simply add `Ω` (U+2126 OHM SIGN) as a second alias for the ohm unit. Since the two characters are usually visually indistinguishable it probably makes sense if they also map to the same unit.

**Comment by eminence** [comment]
That's a nice and simple suggestion.  I just opened a PR with that change
