### ISSUE TITLE
FR: Support currency abbreviations?

### ISSUE THREAD

**Issue by MatthiasGrandl** [sharkdp/numbat#319]
Currently symbols and written out currency names appear to be supported. I would love for abbreviations to be supported as I have no idea how to convert for example to "Canadian dollars". In raycast for example I'd type in `5 eur to cad` and would get the result. With numbat, I don't know how to achieve the same thing.

**Comment by sharkdp** [comment]
You can use abbreviations, but they must be in all-caps: `EUR`, `CAD`, etc.

Note that you can type `info euro`, `info €`, `info canadian_dollar`, … to see all aliases. We also have the full list of supported units (with all aliases) in the documentation: https://numbat.dev/doc/list-units.html

If you would like to use lowercase abbreviations, you can still set them up in your `init.nbt` file:
```
unit eur = EUR
unit cad = CAD
…
```

**Comment by MatthiasGrandl** [comment]
How embarassing I didn't figure this out on my own. Works great thanks!

**Comment by sharkdp** [comment]
It would be easy to implement, but I don't think we want that. There are too many short unit identifiers already. Imagine things like `N` for Newton, `J` for Joule, `W` for Watt. If we make unit matching case insensitive, we would not be able to use `n`, `j`, `w` as identifiers for user-defined variables (or other units).

**Comment by MatthiasGrandl** [comment]
thanks for the reply!! i didn't think about variables. To be honest I have barely scratched the surface of what numbat can do. 

User story: I am building a raycast like launcher for fun and added numbat for quick caculations/conversions. Optional case insensitivity would improve this usecase quite a bit:

<img width="912" alt="image" src="https://github.com/sharkdp/numbat/assets/50196894/040fe51d-7c86-4273-802d-84b045e4ff08">

Anyway thanks for this awesome project. It's super nice to work with this crate and I really appreciate the replies :)

**Comment by mhmdanas** [comment]
I think it's reasonable to add aliases like `eur` and `usd`. Would there be any issues with that?
