### ISSUE TITLE
characters can be used in place of strings in certain parts of the codebase

### ISSUE THREAD

**Issue by hamirmahal** [sharkdp/numbat#332]

**Comment by hamirmahal** [comment]
https://rust-lang.github.io/rust-clippy/master/index.html#/single_char_pattern says

> Performing these methods using a char is faster than using a str.

**Comment by mhmdanas** [comment]
I appreciate all these small improvements you're adding to the codebase, but I think for changes this small you shouldn't need to open issues and can just submit PRs directly. :)

**Comment by hamirmahal** [comment]
Okay, I'll keep that in mind moving forward. Thanks for the feedback.
