### ISSUE TITLE
Add feature to use system `tzdata` instead of vendoring it

### ISSUE THREAD

**Issue by triallax** [sharkdp/numbat#344]
Linux distros already ship `tzdata`, it would be nice if Numbat could optionally be built to use it instead of vendoring `tzdata`. This would also reduce the binary size quite a bit (not that it was ever that big anyway).

`chrono-tz` issue: https://github.com/chronotope/chrono-tz/issues/73

**Comment by sharkdp** [comment]
Looks like https://github.com/kennytm/tzfile already implements everything as required. We could use that on unix. And use chrono_tz on other platforms.

**Comment by sharkdp** [comment]
With #511, this is now supported, actually.
