### ISSUE TITLE
Expressions results in same output although executed at different times

### ISSUE THREAD

**Issue by vbd** [sharkdp/numbat#350]
- numbat 1.10.1
- Windows 11
- numbat as a standalone binary. I've read: https://github.com/sharkdp/numbat/discussions/233

~~~
15.02.2024 14:52:34,31 | D:\workfiles>numbat -e "human(1.25 year)"
456 days + 13 hours + 15 minutes + 56.314800002 seconds
~~~

~~~
15.02.2024 15:22:45,72 | D:\workfiles>numbat -e "human(1.25 year)"
456 days + 13 hours + 15 minutes + 56.314800002 seconds
~~~

Shouldn't have minutes and seconds changed?

**Comment by eminence** [comment]
No, the duration of `1.25 years` is constant, it doesn't take into account the current time.

**Comment by mhmdanas** [comment]
@eminence is completely correct. However, I'm somewhat confused here; what result are you expecting and why are you expecting it @vbd?

**Comment by vbd** [comment]
I was expecting something different from what I entered. Of course 1.25 year converted is constant. Not sure what was going on in my head. I am sorry for the work I have caused you.

**Comment by vbd** [comment]
I was expecting something different from what I entered. Of course 1.25 year is constant. Not sure what was going on in my head. I am sorry for the work I have caused you.

**Comment by mhmdanas** [comment]
No worries, if you have any more questions do please ask us. :)
