### ISSUE TITLE
Not sure why it doesn't work, maybe a typo I don't see?

### ISSUE THREAD

**Issue by vbd** [sharkdp/numbat#351]
- numbat 1.10.1
- Windows 11
- numbat as a standalone binary. I've read: https://github.com/sharkdp/numbat/discussions/233
 
~~~
15.02.2024 15:22:50,39 | D:\workfiles>numbat -e "time(\"14:30\") - time(\"16:02\") -> min"
error: while type checking
  ┌─ <input:1>:1:1
  │
1 │ time("14:30") - time("16:02") -> min
  │ ^^^^ unknown identifier
  │
  = Did you mean 'five'?

Interpreter stopped due to error
~~~

- without escaping `time("14:30") - time("16:02") -> min` it works at numbat.dev
- I checked it several times but can't find my error.

**Comment by mhmdanas** [comment]
The `time` function was added after 1.10.1 was released (https://github.com/sharkdp/numbat/commit/a26bfed8db62a187ff7f01a6704a7a2168087496). https://numbat.dev follows the latest development commit (usually) rather than the latest stable release.

**Comment by vbd** [comment]
Thanks for the clarification. Waiting for the next release. Thank you.
