### ISSUE TITLE
Support mixed units

### ISSUE THREAD

**Issue by bsidhom** [sharkdp/numbat#364]
It would be great if Numbat supported unit lists out of the box [à la Gnu Units](https://www.gnu.org/software/units/manual/html_node/Unit-Lists.html). This allows units to be displayed in an effectively arbitrary "base" consisting of other units.

I understand that this may be tricky or conceptually incompatible with unit typing, but maybe it could make sense to have some short-hand to define unit list functions that convert to `String`. I'm thinking of something similar to the `human()` time function, which currently does this manually in a pretty janky way. (Perhaps the real issue is that custom functions don't have the greatest ergonomics; I'll start a discussion expanding on that.)

Could be nice to have proper support for unit lists as typed entities, though I haven't put much thought into whether that makes sense.

**Comment by sharkdp** [comment]
I am planning to add rudimentary support for (some) mixed unit representations in https://github.com/sharkdp/numbat/pull/501

**Comment by sharkdp** [comment]
Tenatively closing this for now, even if it feels not really "native" yet.

**Comment by sharkdp** [comment]
Reopening this just to close it again, now that we have a much nicer solution, thanks to @Goju-Ryu
