### ISSUE TITLE
Virtual keyboard hides input area on iPhone

### ISSUE THREAD

**Issue by bsidhom** [sharkdp/numbat#366]
This may apply to other mobile environments as well. Basically, if you try to enter text into numbat.dev on a phone, the virtual keyboard pops up. Weirdly, in itself, this _doesn't_ directly obscure the input area, which is still visible. Instead, once you start typing, the virtual console auto-scrolls the live text out of the view. I'm not sure what's causing this.

**Comment by sharkdp** [comment]
Duplicate of #218?

**Comment by bsidhom** [comment]
Ah, yes. And good point about a mobile-oriented interface. That would solve multiple issues in one.
