### ISSUE TITLE
Wrong conversion between rpm and rad/s

### ISSUE THREAD

**Issue by elaye** [sharkdp/numbat#373]
Hello,

First of all thank you for this project, it's really useful and very well made!

I have an issue with the conversion between rpm and rad/s. When I try the following conversion `1 rad/s -> rpm` numbat gives me `60 RPM` even though it should output `9.5493`. It seems there is a `2π` factor missing according to the [wikipedia](https://en.wikipedia.org/wiki/Revolutions_per_minute) article.

**Comment by sharkdp** [comment]
@elaye Any feedback on this?

**Comment by elaye** [comment]
Thank you for your answer, that makes a lot of sense even though it's counter-intuitive!
