### ISSUE TITLE
Missing imperial volume units

### ISSUE THREAD

**Issue by bsidhom** [sharkdp/numbat#375]
The prelude does not seem to include the imperial fluid ounce, imperial pint, imperial gallon, etc., but _does_ have the US customary counterparts.

It would be nice to add these definitions, but I'm not sure how to deal with naming. We should try to avoid confusion as much as possible.

Note that this is unrelated to #116; I'm talking about _individual unit definitions_ differing between US Customary and British Imperial. As far as I'm aware, this discrepancy only exists in volume units, but I'm not sure.

**Comment by sharkdp** [comment]
> It would be nice to add these definitions

:+1: 

> but I'm not sure how to deal with naming. We should try to avoid confusion as much as possible.

I suggest we follow Qalculates naming here, which has `imperial_` prefixes for long unit names and `UK_` prefixes for short unit names. For example:
```
imperial_gallon
UK_gal
```

**Comment by bsidhom** [comment]
Re: #382: after reading up on this, I just discovered that there's the customary tablespoon and "metric tablespoon" (15 mL exactly): https://en.wikipedia.org/wiki/Tablespoon. They apparently use metric tbsp in the UK. Not sure if this is worth adding or where to put it. Nobody appears to call it an "imperial tablespoon". There's a similar situation for the [teaspoon](https://en.wikipedia.org/wiki/Teaspoon#Metric_teaspoon).

**Comment by sharkdp** [comment]
> I just discovered that there's the customary tablespoon and "metric tablespoon" (15 mL exactly): https://en.wikipedia.org/wiki/Tablespoon. They apparently use metric tbsp in the UK. Not sure if this is worth adding or where to put it. Nobody appears to call it an "imperial tablespoon". There's a similar situation for the [teaspoon](https://en.wikipedia.org/wiki/Teaspoon#Metric_teaspoon).

Can you please open a new ticket?
