### ISSUE TITLE
Support for RFC 3339 in target time zone

### ISSUE THREAD

**Issue by bsidhom** [sharkdp/numbat#376]
I'm not able to get times to print in RFC 3339 using the `format_datetime` function:

```
>>> get_local_timezone()

  get_local_timezone()

    = America/Los_Angeles    [String]

>>> format_datetime("%Y-%m-%dT%H:%M:%S%:z", local(now()))

  format_datetime("%Y-%m-%dT%H:%M:%S%:z", local(now()))

    = 2024-02-23T22:01:52+00:00    [String]

>>> now()

  now()

    = Fri, 23 Feb 2024 14:01:54 -0800    [DateTime]
```

According to [the chrono docs](https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers), `%z` and friends should give the _local offset_ relative to UTC. However, it looks like the TZ info is getting dropped before being sent to the formatter and it's always displaying in UTC. (I would also like to add formatters/parsers for the reference format to the prelude, but I'm not sure if others would find that useful.)

**Comment by sharkdp** [comment]
Also, there's no need to do `now() -> local` or `local(now())`. `now()` will return a datetime in the local timezone.

**Comment by sharkdp** [comment]
For `datetime(…)`, do we want to return the datetime object in the specified timezone (current behavior in #378), or in the local timezone (current behavior on `master`)?

**Comment by bsidhom** [comment]
I think it’s best to return the specified TZ offset for consistency. Users can always convert to local after parsing, but it’s otherwise difficult to recover the original offset.

**Comment by sharkdp** [comment]
This should now be fixed: https://numbat.dev/?q=format_datetime%28%22%25Y-%25m-%25dT%25H%3A%25M%3A%25S%25%3Az%22%2C+now%28%29%29%E2%8F%8E
