### ISSUE TITLE
arbitrary precision calculation

### ISSUE THREAD

**Issue by ixzh** [sharkdp/numbat#393]
As a followup project to insect. does numbat support arbitrary precision calculation? for example, log(100!) used to gave the correct result whereas numbat simply gives Inf. Thanks!

**Comment by eminence** [comment]
No, there is not arbitrary precision yet.  Please see https://github.com/sharkdp/numbat/issues/4 and a related discussion in https://github.com/sharkdp/numbat/discussions/368

**Comment by mhmdanas** [comment]
Indeed, seems to give the correct result for me both locally and on https://numbat.dev.

**Comment by ixzh** [comment]
> 100! still works fine, right?
> 
> ```
> >>> log(100!)
> 
>     = 363.739 
> ```

sorry I meant log(1_000_000!) , which worked out correctly in Insect

**Comment by sharkdp** [comment]
Right. Let's continue the discussion in #4.
