### ISSUE TITLE
Random distribution sampling

### ISSUE THREAD

**Issue by Bzero** [sharkdp/numbat#413]
Following up on the discussion in #401 I started to implement functions for random sampling of various distributions in Numbat.

I thought the following distributions would be nice to have: 

- [Continuous uniform distribution](https://en.wikipedia.org/wiki/Continuous_uniform_distribution)
- [Integer uniform distribution](https://en.wikipedia.org/wiki/Discrete_uniform_distribution)
- [Normal distribution](https://en.wikipedia.org/wiki/Normal_distribution)
- [Bernoulli distribution](https://en.wikipedia.org/wiki/Bernoulli_distribution)
- [Binomial distribution](https://en.wikipedia.org/wiki/Binomial_distribution)
- [Geometric distribution](https://en.wikipedia.org/wiki/Geometric_distribution)
- [Poisson distribution](https://en.wikipedia.org/wiki/Poisson_distribution)
- [Exponential distribution](https://en.wikipedia.org/wiki/Exponential_distribution)
- [Log normal distribution](https://en.wikipedia.org/wiki/Log-normal_distribution)
- [Pareto distribution](https://en.wikipedia.org/wiki/Pareto_distribution)

Does this selection sound reasonable or would some of these be considered out of scope?

**Comment by sharkdp** [comment]
> Does this selection sound reasonable or would some of these be considered out of scope?

I'd be happy to support all of these, but it would be great if you could open a PR for just one or two of them at first.. so we can see where and how to integrate those without duplicating a lot of code. Ideally, I would like most of the code to be in Numbat (instead of having all of them as custom FFI functions implemented in Rust). But I understand that the language is probably not ready for this yet?

**Comment by Bzero** [comment]
> I'd be happy to support all of these, but it would be great if you could open a PR for just one or two of them at first.. so we can see where and how to integrate those without duplicating a lot of code.

Sure, that sounds sensible.

> But I understand that the language is probably not ready for this yet?

I think numbat is perfectly suitable for most of them, out of those I already had a look at none was particularly tough to implement in numbat itself. The ones which have an analytical cumulative distribution function can be easily sampled using [inversion sampling](https://en.wikipedia.org/wiki/Inverse_transform_sampling) and I think for many of the others similar transforms exist.

**Comment by sharkdp** [comment]
> I think numbat is perfectly suitable for most of them

Awesome!

**Comment by sharkdp** [comment]
Should we close this, and open a new ticket if we feel something is still missing?
