### ISSUE TITLE
Add info for functions

### ISSUE THREAD

**Issue by eminence** [sharkdp/numbat#421]
A while ago we added support for getting [info about units and variables](https://github.com/sharkdp/numbat/pull/267), 

Now that we're getting some [interesting functions](https://github.com/sharkdp/numbat/pull/416), let's extend the `info` mechanism (and related decorators) to support functions

**Comment by sharkdp** [comment]
Yes — that would be great to have. Thank you for creating the ticket. It would also allow us to auto-generate the list of functions (https://numbat.dev/doc/list-functions.html) and to enrich it with more information.
