### ISSUE TITLE
Conversion of rotational speeds is not correct

### ISSUE THREAD

**Issue by Aym-brz** [sharkdp/numbat#427]
When converting rotational speeds, the result is not correct
>>> 1 rpm -> rad/s

  1 rpm ➞ radian / second

    = 0.0166667 rad/s    [Activity or Frequency]

>>> 1 rad/s -> rpm

  1 radian / second ➞ rpm

    = 60 RPM    [Activity or Frequency]

**Comment by eminence** [comment]
Duplicate of https://github.com/sharkdp/numbat/issues/373
