### ISSUE TITLE
Example from the syntax overview fails in 1.12.0

### ISSUE THREAD

**Issue by T1mVo** [sharkdp/numbat#454]
The following functions from the syntax overview fails when executing locally on 1.12.0 but runs fine in the web app.

```
fn my_sqrt<T: Dim>(q: T^2) -> T = q^(1/2)
```

```
error: while parsing
  ┌─ <input:1>:1:13
  │
1 │ fn my_sqrt<T: Dim>(q: T^2) -> T = q^(1/2)
  │             ^ Expected ',' or '>' in type parameter list
```

**Comment by sharkdp** [comment]
Oh, yes. Sorry about that. We should probably have both the latest docs uploaded somewhere, but also the docs for released versions.

In 1.12.0, generic functions are simply defined via `fn my_sqrt<T: Dim>(q: T^2) -> T = q^(1/2)`, without the `: Dim` bound on the polymorphic type. That is a breaking change that has not been released yet.

**Comment by T1mVo** [comment]
Okay, just wanted to make sure this is not a bug. I agree that there should be additional docs for the released versions or the docs should only get updated with every release.

I think you can close this issue.
