### ISSUE TITLE
1000 - 20%

### ISSUE THREAD

**Issue by andylima** [sharkdp/numbat#494]
Can percentage expressions that work in calculators like Raycast and Numi, such as `1000 - 20%` work in Numbat?

...That would be great. 😃 This is a really common use case.

**Comment by triallax** [comment]
that evaluates just fine in numbat, but not in the way you're probably expecting

`%` in numbat is basically just `1/100`, so `1000 - 20%` is equivalent to `1000 - 20/100` which comes out to 999.8

i presume what you're thinking of would be more like this:

```
>>> 1000 * (1 - 20%)

  1000 × (1 - 20 percent)

    = 800
```

**Comment by sharkdp** [comment]
Related discussions (in the predecessor project of Numbat):
- https://github.com/sharkdp/insect/issues/147#issuecomment-1937290328
- https://github.com/sharkdp/insect/issues/192

It might be worth re-evaluating this. For one, in Numbat, we do not use `%` for modulo anymore. We currently use it as an alias for the percent unit that is simply defined as 0.01, as @triallax mentioned. I'm still not sold on having special syntax support for `%` though, but if someone can come up with a good proposal on how this could work, we can certainly discuss it. What I really *don't* want is a configuration option for this. That's something that Qalculate does:

![image](https://github.com/user-attachments/assets/607253f4-d3ce-43d1-8122-8c064afde008)

Of course you can argue that this makes everyone happy. But I don't like the user experience. And adding configuration options always increases complexity of a software product and makes it harder to test.

One thing we can definitely support is custom functions (and maybe even special syntax?) for those percentage computations. Something like:
```
fn add_percentage<D: Dim>(value: D, percentage: Scalar) = value * (1 + percentage)
fn sub_percentage<D: Dim>(value: D, percentage: Scalar) = add_percentage(value, -percentage)
```
which you can use like this:
![image](https://github.com/user-attachments/assets/d640cdc7-bd4d-4b85-bd78-bcf5b0d37f97)

In fact, you could add those two functions to your `init.nbt` file and use them today.

But of course, this approach suffers from a discoverability problem. How are users going to know about this feature?

**Comment by sharkdp** [comment]
I added a first version of a percentage-calculation API in #609. Feedback is very much welcome.

**Comment by flawrist** [comment]
``` console
$ kalker.exe 1000-1%
990

$ numbat.exe
999.9
```

Oh dear.
