### ISSUE TITLE
Panic when using `abs()` with a non-scalar argument 

### ISSUE THREAD

**Issue by Bzero** [sharkdp/numbat#565]
The `abs()` function panics when attempting to use it on a non-scalar argument:

```nbt
>>> abs(2)

  abs(2)

    = 2

>>> abs(2s)
thread 'main' panicked at numbat/src/ffi/math.rs:28:1:
called `Result::unwrap()` on an `Err` value: IncompatibleUnits(Product { factors: [UnitFactor { unit_id: UnitIdentifier { name: "second", canonical_name: CanonicalName { name: "s", accepts_prefix: AcceptsPrefix { short: true, long: false } }, kind: Base }, prefix: Metric(0), exponent: Ratio { numer: 1, denom: 1 } }] }, Product { factors: [] })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I think this is a regression as I am quite sure this used to work fine in the past.

**Comment by sharkdp** [comment]
Thank you for reporting this. Definitely worked before, yes. Pretty sure I broke it in #534 where I accidentally changed abs alongside with round/floor/.., which is not correct. abs should still be a
```
simple_polymorphic_math_function!(abs, abs);
```

**Comment by Bzero** [comment]
Thanks for the hint, I just opened #572.

I didn't bring back `simple_polymorphic_math_function!` just for this one function but implemented it directly, let me know if you would prefer otherwise.
