### ISSUE TITLE
Shift-enter does not insert newline (opt/alt-enter does)

### ISSUE THREAD

**Issue by rben01** [sharkdp/numbat#574]
The numbat docs say that shift-enter can be used to insert a newline without submitting the current line. However, on my machine (Mac, in both Terminal.app and VSCode), shift-enter does submit the current line. The way to get a plain newline without submitting is alt-enter.

Is this a bug in numbat and/or should the docs be updated?

**Comment by sharkdp** [comment]
This is a difference between the web version and the CLI version. You probably looked at the docs for the web version (https://numbat.dev/doc/web-usage.html) instead of the CLI version (https://numbat.dev/doc/cli-usage.html)?
