### ISSUE TITLE
Constant: tau

### ISSUE THREAD

**Issue by Keavon** [sharkdp/numbat#581]
Having the built-in constant `tau` (equal to `2 * pi`) would be very handy for describing the radians in a full circle instead of needing to use `2 * pi` in many equations like a circle's circumference.

**Comment by sharkdp** [comment]
We have tau defined here: https://github.com/sharkdp/numbat/blob/master/numbat%2Fmodules%2Fmath%2Fconstants.nbt#L10-L12

It's currently only available as a Unicode identifier, but feel free to add a `tau` alias.

In the CLI version, you can also type `\tau<tab>` to have the Unicode character inserted.

**Comment by Keavon** [comment]
Glad to see it's included! I wouldn't have thought to type the Greek letter when `pi` works. Is there a reason only `pi` is aliased as such by default? I suppose it doesn't matter that much to me, since this would all be customizable in a custom usage, but I suppose I'm just curious now :)

**Comment by sharkdp** [comment]
> Is there a reason only pi is aliased as such by default?

I probably just wanted to keep the name "tau" free, since it's often used for time-related quantities in physics (e.g. relaxation times).
