### ISSUE TITLE
Support for more temperature units

### ISSUE THREAD

**Issue by rben01** [sharkdp/numbat#592]
Currently it looks like Numbat only supports Kelvin. It would be great if Celsius, Fahrenheit, and Rankine were also supported.

This might require a change to `UnitKind`, as Celsius and Farenheit don't “start at zero” the way most units do. And the `unit` declaration would be need to be updated to accommodate this with something like `unit degF: Temperature = (K-273.15)*9/5 + 32`. And then Numbat would have to also figure out the inverse function to go the other direction. (Listing everything out, I can perhaps guess why it hasn't been done already... sounds complicated.)

**Comment by sharkdp** [comment]
Please see #184 and #462
