### ISSUE TITLE
Purpose of `\cdot`?

### ISSUE THREAD

**Issue by rben01** [sharkdp/numbat#596]
There is a unicode input shortcut `\cdot` that expands to `U+22C5 Dot Operator`. It seems like this should be a multiplication operator, but instead it's parsed as an identifier character.

```
>>> let x⋅ = 2  # x\cdot

  let x⋅: Scalar = 2
```

It is not present in the match arm here: https://github.com/sharkdp/numbat/blob/4245e752f66df95e095c0cb2cb67eda94a5da8a2/numbat/src/tokenizer.rs#L550

Should it be? Or should `\cdot` expand to the same thing as `\cdotp`, `U+00B7 Middle Dot`?

**Comment by sharkdp** [comment]
The Unicode input feature is inspired (copied?) from julia (https://docs.julialang.org/en/v1/manual/unicode-input/), and they turn `\cdot` into `U+22C5`, so I think we should leave it this way.

I basically just added a couple of characters that I thought could be useful (in the future) for Numbat. I didn't care if they *already* have a purpose right now.

I think it would be sensible to include it in the `TokenKind::Multiply` match arm though? If we do so, let's also update the documentation / syntax highlighting stuff that might refer to different multiplication operators.
