### ISSUE TITLE
Clear command doesn't clear query parameter

### ISSUE THREAD

**Issue by Braayy** [sharkdp/numbat#624]
Hi! I'm loving numbat so far, but i found a problem on the web version of it.

After typing some commands, they get stored on the query parameter for easy sharing, which is awesome, but when you use the `clear` command, the query parameter stays the same.

Is this the intended behaviour?

**Comment by Goju-Ryu** [comment]
I just read through the code handling it. It seems intentional. To clear the url as well as the console, use the `reset` command.

**Comment by Braayy** [comment]
Oh got it, thanks!
