### ISSUE TITLE
How to acknowledge Numbat in a scientific paper?

### ISSUE THREAD

**Issue by archisman-panigrahi** [sharkdp/numbat#633]
Hi, I am in the process of writing a paper, and Numbat was super helpful in doing some of the calculations. How can I acknowledge Numbat? My current plan is the following,
```
We thank the developers of the programming languages Julia [REF] and Numbat, which were utilized for numerical computations in this paper.
```
It would be great if you create a citation link for the github repo as described in https://academia.stackexchange.com/a/172780/128673 and https://x.com/natfriedman/status/1420122675813441540

**Comment by archisman-panigrahi** [comment]
I am working on excitonic condensates. I can share the link the paper once it is in arxiv (it may take a couple of weeks).

I did not write any program with numbat. All the codes were written in Julia. I used numbat to convert the values obtained from the my code into realistic units and vice versa. For example, I know how the kinetic and interaction energy scales with momentum, so I use numbat to evaluate it at one point in my momentum space grid and I use Julia to scale it accordingly everywhere.

Numbat really helps with quickly estimating a quantity when some parameter is changed.

**Comment by Goju-Ryu** [comment]
That sounds really interesting and I will look forward to you sharing it. 

Even though it wasn't a program really it still fits the issue I think. From the issue description:

> All kinds of programs are welcome. Everything from simple one-line expressions to larger computations. Polished or unpolished.

I would love to hear what you would need to be able to write the Julia portions in Numbat too. I realize that Julia is a mature language with a rich ecosystem so it probably isn't feasible in the near future. But any feedback on what could drive numbat in the direction of being able to handle more of those sorts of tasks would help steer the project in the right direction.

**Comment by sharkdp** [comment]
> Hi, I am in the process of writing a paper, and Numbat was super helpful in doing some of the calculations. How can I acknowledge Numbat?

Awesome, thank you for asking. I added a `CITATION.cff` file. Please let me know if you see any issues with it.

> I'm very interested in what the paper is about and how you used Numbat while writing it. If you want to share a bit about your work and experience as it relates to Numbat it would be more than welcome as a comment on this issue: #610.

I can second this.

> I would love to hear what you would need to be able to write the Julia portions in Numbat too. I realize that Julia is a mature language with a rich ecosystem so it probably isn't feasible in the near future. But any feedback on what could drive numbat in the direction of being able to handle more of those sorts of tasks would help steer the project in the right direction.

And this :+1:

**Comment by archisman-panigrahi** [comment]
I will answer the rest of the comments later, but can you also somehow add "A statically typed programming language for scientific computations with first class support for physical dimensions and units " ? 

Otherwise, this is how it appears 
![image](https://github.com/user-attachments/assets/c52090f5-b6fa-48c5-a46a-9b27b8ddd5cb)

**Comment by archisman-panigrahi** [comment]
I edited the .bib entry to the following

```
@misc{Peter_Numbat_2024,
author = {Peter, David},
license = {MIT},
month = oct,
title = {{Numbat}:  A statically typed programming language for scientific computations with first class support for physical dimensions and units },
url = {https://github.com/sharkdp/numbat},
version = {1.14.0},
note = {version: 1.14.0},
year = {2024}
}
```

It produces this

![image](https://github.com/user-attachments/assets/35ccc7ea-3954-430e-ab17-303af40af0ae)

**Comment by archisman-panigrahi** [comment]
> what you would need to be able to write the Julia portions in Numbat too.

I don't think that would be a good idea. Both Julia and Numbat are extremely good at what they currently do, and there is no need to implicate one's features into the other.

But here goes the answer to your question :smile:  
1. MATLAB syntax and (almost) all linear algebra routines in MATLAB
2. Almost all features of matplotlib
3. Speed of C
4. Parallelization support

There are [reasons why Julia was created](https://julialang.org/blog/2012/02/why-we-created-julia/).

However, Numbat is the best tool I know for what it already does. [Please don't make it more complicated](https://en.wikipedia.org/wiki/KISS_principle). There is no need to include matrix diagonalization or differential equation solver routines in Numbat. Those things have been implemented in every other widely-adopted languages used for scientific computing. But, no other tool is as good and reliable at converting dimension-full quantities into one another.

---
> how you used Numbat while writing it

I mainly use Numbat as a unit converter (not as a programming language). 

For example let's say I am trying to model bands in Gallium Arsenide. I have a momentum space lattice with grid spacing 0.02*h_bar/(50 angstrom) and I know the effective mass of electron is 7% of the bare electron mass. What is the kinetic energy in meV at a particular point on the grid? I can easily get the answer with Numbat 
```
(0.02*h_bar/(50 angstrom))^2/(2 * 0.07 * electron_mass) -> meV

  (0.02 h_bar / 50 angstrom)² / (2 × 0.07 × electron_mass) ➞ millielectronvolt

    = 0.00870853 meV    [Energy or Torque]

```
I could in principle use a regular calculator (or even Julia), but Numbat knows all the conversion factors and fundamental constants. Julia wouldn't know that.
Once I know the kinetic energy (which is usually quadratic in momentum) at a single point, I can scale it appropriately at every point on the grid using Julia.

Suppose I have to change some parameters and do the whole calculation again? Simple, it is still a one-liner in Numbat.

I can do a similar procedure for the interaction energy (where I use numbat to get the value of the interaction at a typical point, and do rest of the calculation with Julia).
Finally, I use Julia to self-consistently solve the quantum problem using Hartree-Fock like techniques.

**Comment by sharkdp** [comment]
> I will answer the rest of the comments later, but can you also somehow add "A statically typed programming language for scientific computations with first class support for physical dimensions and units " ?

This is included as `abstract`:

https://github.com/sharkdp/numbat/blob/ccf3aca7034c36822411ff403a4f48f0e2542ad4/CITATION.cff#L14-L17

Maybe there is a better way?

> It produces this with REVTEX, which I like better than the previous one.
> 
> ![image](https://private-user-images.githubusercontent.com/3063132/379475725-35ccc7ea-3954-430e-ab17-303af40af0ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3NDk3NjksIm5iZiI6MTcyOTc0OTQ2OSwicGF0aCI6Ii8zMDYzMTMyLzM3OTQ3NTcyNS0zNWNjYzdlYS0zOTU0LTQzMGUtYWIxNy0zMDNhZjQwYWYwYWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjRUMDU1NzQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTMxNzZiY2IzYWZiMjgwODI1MjIwMGEzZmFkMDdhOTY1MTY0NTdjYTQwODk3ZDdmODg3ZjNjZTFiMzI3ZTk4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.zyvj1GJP6TN7IHZsfI9Zi5Y8HZ24wkChvRBolyqrZ7Q)

That looks great — thank you

**Comment by archisman-panigrahi** [comment]
Here is the paper. https://arxiv.org/pdf/2411.08091

It would be nice if the Numbat documentation is published at a journal like https://scipost.org/SciPostPhysCodeb at some point.

**Comment by sharkdp** [comment]
Thank you for the reference and good luck with your paper. Reminds me of the good old times when I was also [publishing in `cond-mat`](https://arxiv.org/a/peter_d_1.html) :smile:

**Comment by archisman-panigrahi** [comment]
It got published https://doi.org/10.1103/v6r7-4ph9

**Comment by sharkdp** [comment]
PRL — wow. Congratulations!
