### ISSUE TITLE
Adding some more math functions

### ISSUE THREAD

**Issue by rben01** [sharkdp/numbat#640]
Some functions I was looking for but couldn't find in Numbat:

* stats
  * the erf function
  * z-score calculator and inverse z-score calculator (probability → n standard devs and n standard devs → probability)
* combinatorics
  * binomial coefficient aka “n choose k”
  * factorial (there is the `!` postfix operator but not a standalone function (that I could find))
  * various sequences like Fibonacci, Lucas, Catalan

**Comment by sharkdp** [comment]
can we merge this into #144?




> * factorial (there is the `!` postfix operator but not a standalone function (that I could find))

Just as a remark… we have `gamma`; which can be used to implement `factorial`.

**Comment by sharkdp** [comment]
done
