### ISSUE TITLE
Numbat doesn’t build on `main` anymore

### ISSUE THREAD

**Issue by irevoire** [sharkdp/numbat#648]
Hey,

I wanted to get some work done on numbat, but I can’t `cargo build` it on the latest commit:
```
128 irevoire@MacBook-Pro-5 ~/numbat ⭐️ % cargo build --release --locked
   Compiling rustyline v13.0.0
   Compiling toml v0.8.19
   Compiling terminal_size v0.3.0
   Compiling numbat v1.14.0 (/Users/irevoire/numbat/numbat)
error[E0063]: missing field `kind` in initializer of `completion::Pair`
   --> /Users/irevoire/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rustyline-13.0.0/src/completion.rs:404:38
    |
404 |                         entries.push(Pair {
    |                                      ^^^^ missing `kind`

For more information about this error, try `rustc --explain E0063`.
error: could not compile `rustyline` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by sharkdp** [comment]
Hm, I can not reproduce this locally. And CI also runs fine: https://github.com/sharkdp/numbat/actions

**Comment by irevoire** [comment]
Huum yeah I don’t know, anyway after updating a bunch of dependencies, it works https://github.com/sharkdp/numbat/pull/649

**Comment by sharkdp** [comment]
But what is going on. Line 404 of rustyline v13.0.0 isn't doesn't even contain that `entries.push(…)` statement:

https://github.com/kkawakam/rustyline/blob/64e1082750a991b9fe18383a954f5eab0a29e039/src/completion.rs#L404

**Comment by irevoire** [comment]
Yeah, I looked at `doc.rs` to be sure I got the matching source code, but it doesn’t match either: https://docs.rs/crate/rustyline/13.0.0/source/src/completion.rs#404

I can’t even find the corresponding sha I got from `crates.io` in my error message 🤔 : 6f17d22bba15001f

I had no idea what was going on tbh, so I tried `cargo build --locked`, `cargo clean`, and `cargo update` but was still getting the same error message, and that’s when I decided to update the version in the cargo.toml myself.

**Comment by sharkdp** [comment]
Anyway. I'm okay with updating dependencies. Let's just close this then.
