### ISSUE TITLE
Numbat Organization

### ISSUE THREAD

**Issue by bistcuite** [sharkdp/numbat#653]
Hi.
I hope you’re doing well. I’ve been following your project on GitHub, and I think it’s a fantastic initiative. As the project continues to grow, I wanted to suggest moving the repository to a GitHub organization.
By transferring the repository to an organization, you’ll be able to better manage the project’s contributions, facilitate collaboration with multiple contributors, and scale the project more effectively. It also gives the project a more professional structure, allowing for improved visibility and better access control.
I believe this could help the project reach new heights and foster a larger community around it.

**Comment by sharkdp** [comment]
Thank you for the feedback. I'm not sure I'm following the argumentation.

> By transferring the repository to an organization, you’ll be able to better manage the project’s contributions

why?

> facilitate collaboration with multiple contributors

?

> and scale the project more effectively

what does that mean?
