### ISSUE TITLE
Add conversion to mixed units

### ISSUE THREAD

**Issue by Arthri** [sharkdp/numbat#667]
Qalculate has allows the user to specify auto conversion settings. There are numerous possible settings but the ones relevant to this suggestion is 0 (none) and 4 (mixed).

Currently, Numbat behaves the same as Qalculate with auto conversion set to none or 0. I suggest to add an option to convert to mixed units, so that the output can be better visualized in certain scenarios.

In Qalculate, when a number is converted into mixed units, the largest unit is the one specified. For example,
```
> 123456s -> h

  123456 * second = 34 h + 17 min + 36 s

> 123456s -> minute

  123456 * second = 2057 min + 36 s
```

Notice that neither command outputted had days in the output. Numbat can achieve something similar at the moment, with `-> human` however, this only applies to select cases. I propose adding a generalized option for all units

To my knowledge, this has been mentioned before in a comment https://github.com/sharkdp/numbat/issues/219#issuecomment-2000217567

**Comment by sharkdp** [comment]
It's probably not quite what you're looking for, but have you seen https://numbat.dev/doc/list-functions-other.html#mixed-unit-conversion
